#!/usr/bin/env php
<?php

declare(strict_types=1);

use Infocyph\Foundation\Command\CommandDispatcher;

$autoload = __DIR__ . '/vendor/autoload.php';
if (!is_file($autoload)) {
    fwrite(STDERR, "Unable to locate vendor/autoload.php; run composer install first.\n");
    exit(1);
}

require $autoload;

exit(CommandDispatcher::project(
    ['base_path' => __DIR__],
    displayName: 'Infbyte',
)->run($argv));
